<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
    </header>
    <main>
        <div class="container">
            <!-- 
                L'attribut "enctype" spécifie comment les données du formulaire doivent être encodées avant d'être envoyés au serveur lorsque le formulaire est soumis. Cet attribut est particulièremeent important lorsque bous avez des champs de formulaire de type "file".
                Lorsque vous définissez `enctype="multipart/form-data"`, cela signifie que les données du formulaire seront encodés sous la forme d'un contenu binaire multipart.F Ce type d'encodage est utilisé pour les formulaire contenant des champs de téléchargement de fichiers, car il permet de transférer des fichiers binaires, tels que les images, les vidéos, etc..., en plus de données de texte.
             -->
            <form action="server.php" method="post" enctype="multipart/form-data">
                <div class="mb-3">
                  <input type="hidden" name="MAX_FILE_SIZE" value="3000000">
                    <label for="file" class="form-label">Importez un fichier</label>
                    <input type="file" class="form-control" id="file" name="photo_profile">
                </div>
                <button class="btn btn-primary">Submit</button>
            </form>
          <a href="download.php?file=img-upload-1693300207.jpg">Télécharger l'image</a>  
          </div>
    </main>
</body>
</html>